/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as governorConrtactSol from "./GovernorConrtact.sol";
export { TimeLock__factory } from "./TimeLock__factory";
