/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as governorConrtactSol from "./GovernorConrtact.sol";
export type { governorConrtactSol };
export type { TimeLock } from "./TimeLock";
